
 CREATE TABLE users (
	id INTEGER NOT NULL AUTO_INCREMENT,
    googleId VARCHAR(1000),
    `name` VARCHAR(255),
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);

CREATE TABLE transactions (
	id INTEGER NOT NULL AUTO_INCREMENT,
    Sign BOOLEAN,
    Balance  DECIMAL(15,2),
	Amount DECIMAL(15, 2),
    Description VARCHAR(1023),
    Category VARCHAR(25),
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UserId INTEGER,
    FOREIGN KEY (UserId) REFERENCES users(id),
    PRIMARY KEY (id)
);



